apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-account
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-account
      project: wallet-api-account
  template:
    metadata:
      labels:
        app: api-account
        project: wallet-api-account
    spec:
      containers:
      - env:
        - name: PARAMS
          value: |-
            -Dserver.port=8000
            -Dspring.application.namespace=wallet-api-prod
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
            -Dnacos.server.address=192.168.88.121:8848
            -Dspring.cloud.nacos.username=nacos
            -Dspring.cloud.nacos.password=${nacos-password}
        - name: JAVA_OPTS
          value: -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=70
            -Xms1G -Xmx1G -Xss256k
        envFrom:
        - secretRef:
            name: nacos-secret
        image: IMAGE
        imagePullPolicy: Always
        name: api-account
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 5000
          name: debug
          protocol: TCP
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
      imagePullSecrets:
      - name: pull-wallet-image
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-account
  namespace: prod
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  - name: debug
    port: 5000
    protocol: TCP
    targetPort: debug
  selector:
    app: api-account
    project: wallet-api-account
  type: NodePort
